version: 2
jobs:
  build:
    working_directory: /app
    docker:
    - image: docker.io/library/alpine:3.5
    steps:
    - checkout
    - run:
        name: Ensure bats setup
        command: |
          apk add --no-cache curl bash
          cd /tmp
          curl -L https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz | tar -xz
          ./bats-0.4.0/install.sh /usr/local
    - run:
        name: Run project setup tests
        command: bats spec/ensure_setup_is_working